### ISSUE TITLE
AttributeError: 'str' object has no attribute 'shape'

### ISSUE THREAD

**Issue by RickyGunawan09** [AbhishekAnand18/ImageTextRecognition#1]
can you help me with this problem? 
I want to recreate this image text recognition but I have an error when I want to run the fit_generator method

 
![image](https://user-images.githubusercontent.com/65578014/97153156-9feb3780-17a4-11eb-8ae4-acce3b117a5f.png)

the problem is in train_gen.next_batch()
but I don't know what's wrong. 'cause I just copy your work but I'm using my datasets.  
can you help me?
thank you.

**Comment by AbhishekAnand18** [comment]
Hi Ricky,

Can 

> can you help me with this problem?
> I want to recreate this image text recognition but I have an error when I want to run the fit_generator method
> 
> ![image](https://user-images.githubusercontent.com/65578014/97153156-9feb3780-17a4-11eb-8ae4-acce3b117a5f.png)
> 
> the problem is in train_gen.next_batch()
> but I don't know what's wrong. 'cause I just copy your work but I'm using my datasets.
> can you help me?
> thank you.

Could you let me know about the images you're using in your data set? they need to be pre-processed a bit before running this piece of code.

**Comment by AbhishekAnand18** [comment]
The Image Data need to pre-processed before running the piece of code.

**Comment by keyansaravanan** [comment]
![image](https://user-images.githubusercontent.com/70126510/116787301-e22d6280-aac0-11eb-91c5-63754ea33824.png)

**Comment by keyansaravanan** [comment]
same here how to solve it
does the preprocessing steps has been added?

**Comment by AbhishekAnand18** [comment]
> same here how to solve it
> does the preprocessing steps has been added?

Yes, they have been added. Try adding the files in appropriate folders and run the notebook from the beginning, all the preprocessing steps have been added.
